[package]
name = "montas"
version = "0.1.0"
authors = ["MrWint"]
links = "gambatte"
build = "build.rs"

[dependencies]
bitflags = "1.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
flate2 = "1.0"
num_cpus = "1.8.0"
