[package]
name = "gambatte"
version = "0.1.0"
authors = ["MrWint"]
edition = "2018"
links = "gambatte"
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
bitflags = "1.0"
byteorder = "1.2.7"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
